site_name: Calkulate
site_author: Matthew P. Humphreys
site_description: Calkulate: seawater total alkalinity from titration data
copyright: Copyright &copy; 2019 Matthew P. Humphreys (GNU GPLv3).

site_url: https://calkulate.readthedocs.io/
repo_url: https://github.com/mvdh7/calkulate

lang: en
theme: readthedocs

nav:
  - Overview: index.md
  - Quick-start guide: quick-start.md
  - Calkulate modules:
      - .density - seawater and acid densities: modules/density.md
  - MATLAB: matlab.md
