site_name: Calkulate
site_author: Matthew P. Humphreys
site_description: Seawater total alkalinity from titration data.
copyright: Copyright &copy; 2019 Matthew P. Humphreys (GNU GPLv3).

site_url: https://calkulate.readthedocs.io/
repo_url: https://github.com/mvdh7/calkulate

theme: readthedocs

nav:
  - Overview and installation: index.md
  - Variables and conventions: conventions.md
  - Alkalinity solvers: solvers.md
  - Titrant calibration: calibration.md
  - Workflow examples: workflow.md
  - Version history: versions.md
  - References: references.md
